version: 2
jobs:
  build-and-test:
    macos:
      xcode: "9.0"
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: brew tap bazelbuild/tap
      - run: brew tap-pin bazelbuild/tap
      - run: brew install bazel
      - run: pip3 install numpy
      - run: brew install libtool
      - run: mkdir -p ~/graphs
      - run: gsutil -m cp gs://tunity-packages/nets/retinanet/mobilenet/deep_tv_detector.pb ~/graphs
      - run: git checkout remotes/origin/r1.9
      - run: tensorflow/contrib/makefile/build_all_ios.sh -a arm64
      - run: bazel build --copt="-DUSE_GEMM_FOR_CONV" tensorflow/python/tools/print_selective_registration_header
      - run: bazel-bin/tensorflow/python/tools/print_selective_registration_header --graphs=~/graphs/deep_tv_detector.pb > tensorflow/core/framework/ops_to_register.h
      - run: tensorflow/contrib/makefile/compile_ios_tensorflow.sh -f "-Os -DSELECTIVE_REGISTRATION" -a arm64 -n tensorflow/contrib/makefile/downloads/nsync/builds/lipo.ios.c++11/nsync.a -a arm64

      - run: cp

      - store_artifacts:
          path: .circleci/artifacts



workflows:
  version: 2
  build-test-adhoc:
    jobs:
      - build-and-test
